source:                .
destination:           ./_site
include:               
  - _pages

lang:                  en
title:                 '@ryvor'
description:           'Software developer'
copyright:             © 2023. All rights reserved.

#accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(50, 50, 56)
theme_color:           rgb(25,55,71)

google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font-code:             ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace;

plugins:
  - jekyll-avatar
author:
  social:
    github:            ryvor
    twitter:           _ryvor
github_username:       ryvor

hydejack:
  post_addons:         [about, newsletter, related, random, comments]
  project_addons:      [about, newsletter, other, comments]

  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false

  use_lsi:             true
  cookies_banner:      true
  advertise:           false
  hide_dates:          false
  hide_last_modified:  false

  image:
    path:              /assets/img/logo.png

  offline:
    enabled:           true
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

menu:
  - title: Posts
    url:   /Posts/
  - title: Projects
    url:   /Projects/